export enum SocketEvents {
  CONNECTION = "connection",
  CONNECT = "connect",
  DISCONNECT = "disconnect",

  CONFIGURAR_USUARIO = "CONFIGURAR_USUARIO",
  USUARIOS_CONECTADOS = "USUARIOS_CONECTADOS",
  MENSAJE_TODOS = "MENSAJE_TODOS",
  MENSAJE_PRIVADO = "MENSAJE_PRIVADO",
  DESCONECTAR_USUARIO = "DESCONECTAR_USUARIO",
}
